### ISSUE TITLE
Bed todo list

### ISSUE THREAD

**Issue by SirCmpwn** [KnightOS/KnightOS#335]
Things I need to do in the `ui-rewrite` branch before it can be merged:

* [x] Scrolling
  * [ ] Horizontal
  * [x] Vertical
    * [ ] Bug with scrolling up into a blank line?
* [ ] Fix backspace issues
* [ ] fileman support for opening files via menu
* [ ] Save file dialog, probably through fileman
  * [ ] Save as distinct from save for existing files
  * [ ] Overwriting a file leads to a crash
