### ISSUE TITLE
Scas 1.0 tracker

### ISSUE THREAD

**Issue by pixelherodev** [KnightOS/KnightOS#405]
- [ ] Check hashes against sass-built kernel for each platform

This means using a static KERNEL_VERSION with sass and noting down the hashes of every produced binary. Then, we need to use that same static KERNEL_VERSION with scas and ensure the hashes match. If they don't, looking at the symbol file and debug output should be enough to narrow down the cause.

- [ ] Ensure symbol files are accurate

Symbol files will differ from sass', if only because they don't have the 'produced by sass' line. Furthermore, sass produces symbol files with all-lowercase symbol names, while scas preserves the casing.

For 1.1:

- [ ] Actually implement .echo
- [ ] Fix memory leaks in paths not taken by the kernel
- [ ] Generating listing files
- [ ] Fuzz?

**Comment by pixelherodev** [comment]
This should be a week away, tops. It's entirely possible scas is already good enough (hence the release candidate), but it's also possible more work will be needed.

**Comment by pixelherodev** [comment]
Okay, I've been doing work on libscas, hence the delay. I'm narrowing the scope of this to *just* have the binary good enough for the kernel for all supported platforms. Anything else is pushed off to 1.1

**Comment by pixelherodev** [comment]
Update: after testing on the TI84+, I fixed a few more bugs (hence scas is now on 1.0-rc4). Pages 0 and 1 are 100% correct, but there is a minor difference in the output of the floating point math routines in page 2.

**Comment by pixelherodev** [comment]
The kernel is clearly not as representative as I'd thought; castle is disturbingly broken under 1.0-rc4. A full test of KnightOS/KnightOS is needed before marking this as final, and a solution to catch regressions needs to be in place for 1.1.
